# Generated by Django 4.1.5 on 2023-01-29 10:13

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=300)),
                ('username', models.CharField(max_length=500)),
                ('first_name', models.CharField(max_length=500)),
                ('last_name', models.CharField(max_length=500)),
                ('all_members_are_administrators', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='sender',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=500)),
                ('username', models.CharField(max_length=500)),
                ('is_bot', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='TextMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('message_id', models.BigIntegerField()),
                ('date', models.DateTimeField()),
                ('text', models.TextField()),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='botreader.chat')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='botreader.sender')),
            ],
        ),
    ]
