# Generated by Django 4.1.5 on 2023-01-29 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('botreader', '0003_updateid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='all_members_are_administrators',
        ),
    ]
