# Generated by Django 4.1.5 on 2023-01-29 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botreader', '0005_textmessage_reply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textmessage',
            name='message_id',
            field=models.BigIntegerField(unique=True),
        ),
    ]
