# Generated by Django 4.1 on 2023-03-16 10:59

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('botreader', '0006_alter_textmessage_message_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('uid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('username', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='users', to='botreader.chat')),
                ('inviterUser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invitedUsers', to='botreader.user')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='botreader.user')),
            ],
        ),
    ]
