# Generated by Django 4.1 on 2023-03-30 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("botreader", "0007_add_user_and_usergroup"),
    ]

    operations = [
        migrations.AddField(
            model_name="usergroup",
            name="event_type",
            field=models.CharField(
                choices=[("ENTRY", "Entry"), ("EXIT", "Exit")],
                default="ENTRY",
                max_length=10,
            ),
        ),
    ]
