# Generated by Django 4.1 on 2023-05-17 10:31

from django.db import migrations, models
import django.db.models.deletion


def move_sender_data_to_another_field_in_text_message(apps, schema_editor):
    Sender = apps.get_model('botreader', 'Sender')
    User = apps.get_model('botreader', 'User')
    TextMessage = apps.get_model('botreader', 'TextMessage')
    senders = Sender.objects.all()
    for sender in senders:
        try:
            user = User.objects.get(uid=sender.id)
        except User.DoesNotExist as e:
            user = User.objects.create(
                uid=sender.id, name=sender.first_name, username=sender.username)
        text_messages = TextMessage.objects.filter(sender=sender).all()
        for text_message in text_messages:
            text_message.sender_user = user
            text_message.save()


class Migration(migrations.Migration):

    dependencies = [
        ("botreader", "0008_add_event_type_field_to_usergroup"),
    ]

    operations = [
        migrations.AddField(
            model_name="textmessage",
            name="sender_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="botreader.user",
            ),
        ),
        migrations.RunPython(
            move_sender_data_to_another_field_in_text_message),
        migrations.RemoveField(
            model_name="textmessage",
            name="sender",
        ),
        migrations.RenameField(
            model_name="textmessage",
            old_name="sender_user",
            new_name="sender",
        ),
        migrations.DeleteModel(
            name="sender",
        ),
    ]
