# Generated by Django 4.1 on 2023-05-23 07:29

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('botreader', '0010_add_chat_admins'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserGroup',
            new_name='ChatEvent',
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('exited', models.BooleanField(default=False)),
                ('last_membership_date', models.DateTimeField(null=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='botreader.chat')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='botreader.user')),
            ],
        ),
    ]
