# Generated by Django 4.1 on 2023-05-29 15:54

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("botreader", "0013_alter_chat_members_alter_textmessage_chat_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArchivedTextMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sid", models.CharField(max_length=50)),
                ("chat_id", models.CharField(default="", max_length=250)),
                ("text", models.TextField()),
                (
                    "hashtags",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100),
                        blank=True,
                        size=None,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="textmessage",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "----"),
                    ("QUESTION", "Question"),
                    ("ANSWER", "Answer"),
                    ("ADVERTISEMENT", "Advertisement"),
                    ("STATEMENT", "Statement"),
                    ("TRASH", "Trash"),
                ],
                default="",
                max_length=15,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="first_name",
            field=models.CharField(default="", max_length=60),
        ),
        migrations.AddField(
            model_name="user",
            name="last_name",
            field=models.CharField(default="", max_length=60),
        ),
        migrations.AddField(
            model_name="user",
            name="mobile",
            field=models.CharField(default="", max_length=20),
        ),
    ]
