# Generated by Django 4.1 on 2023-05-31 09:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "botreader",
            "0014_archivedtextmessage_textmessage_type_user_first_name_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="type",
            field=models.CharField(
                choices=[
                    ("", "----"),
                    ("MANSOOR", "Mansoor"),
                    ("NASER", "Naser"),
                    ("NADER", "Nader"),
                ],
                default="",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="textmessage",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "----"),
                    ("QUESTION", "Question"),
                    ("ANSWER", "Answer"),
                    ("SUGGESTION", "Suggestion"),
                    ("ADVERTISEMENT", "Advertisement"),
                    ("STATEMENT", "Statement"),
                    ("SELL", "Sell"),
                    ("TRASH", "Trash"),
                ],
                default="",
                max_length=15,
            ),
        ),
    ]
